### ISSUE TITLE
Could you please create Readme file?

### ISSUE THREAD

**Issue by sohag1990** [islamic-network/api.alquran.cloud-db#1]
Assalamualikum.
Could you please create instruction to run your docker file and docker composer file? Hope this will be helpful for new docker users who what to work on the Quran app.

Jakalallahu

**Comment by meezaan** [comment]
Alaykum Salaam Sohag,

This is more for internal use, really, and it exists only to trigger the Docker Hub build.

To use this database, see the docker-compose file in https://github.com/islamic-network/api.alquran.cloud.

This repo just publishes a database image at https://hub.docker.com/repository/docker/islamicnetwork/api.alquran.cloud-db.

I will try and add a README file, though.
